version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    depends_on:
      - certbot

  certbot:
    build:
      context: ./certbot
    container_name: certbot
    volumes:
      - ./nginx:/etc/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c " trap exit TERM; while :; do
        certbot renew --webroot -w /var/www/certbot --quiet;
        sleep 12h & wait $${!};
      done; "
