name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push NGINX Image
      run: |
        docker build -f Dockerfile-certbot -t your-dockerhub-repo/certbot .
        docker push your-dockerhub-repo/certbot

    - name: Deploy Docker Compose on AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          # Clonar el repositorio en la máquina de AWS
          cd /path/to/your/project || git clone https://github.com/your-repo/project.git /path/to/your/project
          cd /path/to/your/project
          git pull origin master

          # Construir y levantar los servicios con Docker Compose
          docker-compose pull
          docker-compose up -d --remove-orphans
          
          # Verificar estado
          docker-compose ps
        EOF
