name: Deploy Angular App with SSL

on:
  push:
    branches:
      - master  # O la rama principal de tu repositorio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Construir la imagen Docker de la app Angular
      - name: Build Angular app Docker image
        run: |
          docker build -f Dockerfile -t angular_app .

      # 4. Subir la imagen a Docker Hub (opcional)
      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: leonelarandap/angular_app:latest  # Ajusta tu repositorio de Docker Hub

      # 5. Configuración de Certbot (Generación de certificados)
      - name: Request SSL Certificates with Certbot
        run: |
          docker-compose -f docker-compose.yml run --rm certbot \
            certonly --webroot -w /var/www/certbot -d sistemagf.cl -d www.sistemagf.cl

      # 6. Iniciar el contenedor con la app y NGINX
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      # 7. (Opcional) Prueba de que la aplicación está corriendo
      - name: Check if the application is running
        run: |
          curl -sSf http://sistemagf.cl || exit 1

      # 8. Enviar notificación (opcional, si se desea)
      - name: Send Notification on Success (opcional)
        run: |
          echo "Deployment to production was successful!" | mail -s "Deployment Status" youremail@example.com
